version: 0.0.1
apimServiceName: SimpleAPIService
apiVersionSets:
    - id: SimpleAPIVersionSet
      displayName: SimpleAPI
      description: Simple API
      versioningScheme: Query
      versionQueryName: versionQuery
      versionHeaderName: versionHeader
apis:
    - name: SimpleAPI
      apiVersion: v1
      apiVersionDescription: My first version
      openApiSpec: C:\SimpleAPI\swagger.json
      policy: C:\SimpleAPI\api-policy.xml
      suffix: conf
linked : true
linkedTemplatesBaseUrl : https://myteststorage5555.blob.core.windows.net/mytestblob5555
outputLocation: C:\SimpleAPI\templates
